const {test}=require("node:test");
const assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const root=path.resolve(__dirname,"..");
const sandbox={URL};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,"extension/core.js"),"utf8"),sandbox);
const C=sandbox.CanvasLocalCore;
test("defaults: global web scope and five independent booleans",()=>{const c=C.normalize();assert.equal(c.schemaVersion,2);assert.equal(c.origins,undefined);for(const k of C.FLAGS)assert.equal(c[k],true)});
test("normalization rejects malformed input",()=>{assert.equal(C.normalize(null).enabled,true);assert.equal(C.normalize({focus:"false"}).focus,true)});
test("reject file/chrome/javascript and embedded credentials",()=>{for(const s of ["file:///a","chrome://extensions","javascript:alert(1)","https://u:p@example.com"])assert.equal(C.originOf(s),null)});
test("public HTTP and HTTPS origins",()=>{assert.equal(C.originOf("https://canvas.example.com/courses/1"),"https://canvas.example.com");assert.equal(C.originOf("http://example.com/a"),"http://example.com")});
test("old whitelist migration retains disabled flags without retaining site gates",()=>{const c=C.normalize({schemaVersion:1,origins:["https://a.com"],enabled:false,focus:false,panel:false});assert.equal(c.origins,undefined);assert.equal(c.enabled,false);assert.equal(c.focus,false);assert.equal(c.panel,false);assert.equal(c.schemaVersion,2)});
test("all ordinary paths plus fallback documents, excluding protected pages",()=>{for(const u of ["https://other.test/login","http://example.com/courses/abc"])assert.equal(C.allowed(u),true);for(const u of ["chrome://extensions","file:///a","https://chromewebstore.google.com/detail/x"])assert.equal(C.allowed(u),false);for(const u of ["about:blank","about:srcdoc","data:text/html,a","blob:https://example.com/id"])assert.equal(C.frameAllowed(u),true);assert.equal(C.frameAllowed("about:settings"),false)});
test("independent panel/toolbar flags do not disable core",()=>{const c=C.normalize({panel:false,toolbar:false});assert.equal(c.focus,true);assert.equal(c.cleaner,true);assert.equal(c.panel,false)});
test("production manifest declares HTTP/HTTPS automatic access, no remote execution",()=>{const m=JSON.parse(fs.readFileSync(path.join(root,"extension/manifest.json")));assert.equal(m.manifest_version,3);assert.deepEqual(m.host_permissions,["https://*/*","http://*/*"]);assert.equal(m.optional_host_permissions,undefined);assert.equal(m.externally_connectable,undefined);assert.deepEqual(m.permissions,["storage","scripting","activeTab"]);assert.match(m.content_security_policy.extension_pages,/connect-src 'none'/)});
test("extension has no network/account/AI request code",()=>{const s=fs.readdirSync(path.join(root,"extension")).filter(f=>f.endsWith(".js")).map(f=>fs.readFileSync(path.join(root,"extension",f),"utf8")).join("\n");assert.doesNotMatch(s,/\bfetch\s*\(|XMLHttpRequest|uninstallSelf|kill-switch|\/ai\/answer|supabase/);assert.doesNotMatch(s,/postMessage\s*\(/)});
test("all product JavaScript compiles",()=>{for(const f of fs.readdirSync(path.join(root,"extension")).filter(x=>x.endsWith(".js")))new vm.Script(fs.readFileSync(path.join(root,"extension",f),"utf8"),{filename:f})});

test("brand is consistent in manifest and popup",()=>{const m=JSON.parse(fs.readFileSync(path.join(root,"extension/manifest.json")));const h=fs.readFileSync(path.join(root,"extension/popup.html"),"utf8");assert.equal(m.name,"Canvas Phantom · 幻影");assert.equal(m.action.default_title,m.name);assert.match(h,/<h1>Canvas Phantom<\/h1>/);assert.match(h,/class="logo">CP</);assert.match(h,/class="tag">FREE</);assert.doesNotMatch(h,/Canvas Local|>CL<|>LOCAL</)});
test("toolbar and diagnostic labels use Phantom while internal IDs stay compatible",()=>{const s=fs.readFileSync(path.join(root,"extension/content.js"),"utf8");const b=fs.readFileSync(path.join(root,"extension/background.js"),"utf8");assert.match(s,/Canvas Phantom 页面功能/);assert.match(s,/Canvas Phantom · 运行状态/);assert.match(s,/title="Canvas Phantom · 幻影">CP</);assert.match(s,/__CANVAS_LOCAL_UI_V1__/);assert.match(b,/canvas-local-main/);assert.doesNotMatch(s+b,/Canvas Local/)});
test("package, manifest and footer versions agree",()=>{const m=JSON.parse(fs.readFileSync(path.join(root,"extension/manifest.json")));const p=JSON.parse(fs.readFileSync(path.join(root,"package.json")));const h=fs.readFileSync(path.join(root,"extension/popup.html"),"utf8");assert.equal(m.version,p.version);assert.ok(h.includes("v"+m.version+" ·"))});
